server:
  port: 8189
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: gateway-service
          uri: lb://API-UMS
          predicates:
            - Path=/api-ums/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8182/eureka/